### ISSUE TITLE
Login page spring security

### ISSUE THREAD

**Issue by sjdmulde** [ddtxra/spring-security-auth0#6]
Hi,

I'm missing a login page in the example. Auth0 requires a callback url and i see no integration between the callback and spring security.

I've tried adding a custom login page, but without success. The authorization header is alway null.

Thanks,
Stijn

**Comment by ddtxra** [comment]
Hello Stijn,
I guess you are missing the login window because you must edit src/main/resources/auth0.properties with your client id, secret and domain coming from auth0 dashboard. On the Auth0 dashboard you must add http://localhost:8080/spring-auth0-example/ as an App Callback URL.

The callback (where the JWT is received) is handled directly on the client side by the auth0 widget (https://github.com/auth0/widget) which is a modal window (not a real URL). The integration with Spring Security comes later (once the auth0 widget already handled the callback and has the JWT). For every request the JWT is sent to the Spring API and is validated and decoded by spring security. If the validation succeed an authentication object is created and put on the Spring Security Context.
Note that Auth0 has forked this project and is now maintaining the official version at: https://github.com/auth0/spring-security-auth0
